version: 2.1

orbs:  
  aws-cli: circleci/aws-cli@2.0.3
#  ------------------------------------------------------------------------------------------------------------------------------------------
#  defaults (like global variables dubstiuted below)
#  ------------------------------------------------------------------------------------------------------------------------------------------
docvarnode: &dok_node
    docker:
      - image: circleci/node:13.8.0

docvaraws: &dok_awscli
    docker:
      - image: amazon/aws-cli    

docansibl: &dok_ansible
    docker:
      - image: python:3.7-alpine3.11 

docjava: &dok_java
    docker:      
      - image: cimg/openjdk:16.0.2

#  ------------------------------------------------------------------------------------------------------------------------------------------
#  list of parameters
#  ------------------------------------------------------------------------------------------------------------------------------------------

parameters:
  workflow-id:
    type: string
    default: "${CIRCLE_WORKFLOW_ID}"


#  ------------------------------------------------------------------------------------------------------------------------------------------
#    Jobs list startd from here    
#
#
#  ------------------------------------------------------------------------------------------------------------------------------------------

jobs:

# -----------------------------  Linting step for docker file   -----------------------------------------------------------------------------
  lint-dockerfile:
    <<: *dok_node
    steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
              sudo chmod +x /bin/hadolint
        - run:
            name: Run Lint
            command: |
              hadolint Dockerfile        

# -----------------------------  build the docker image   ----------------------------------------------------------------------------------
  build-dockerimage:
    <<: *dok_java    
    steps:
      - checkout
      - setup_remote_docker:  
            version: 19.03.13
            docker_layer_caching: true
      - run:
            name: Build Docker Image
            command: |
              export TAG=v${CIRCLE_BUILD_NUM}
              export IMAGE_NAME=capstone
              docker build -t scienceselva/$IMAGE_NAME:$TAG .  

# -------------------------------------------------------------------------------
#
#         WORKFLOW  STEPS STARTS FROM HERE
#
# -------------------------------------------------------------------------------
workflows:
  default:
    jobs:
      - lint-dockerfile
      - build-dockerimage:
        requires: [lint-dockerfile]

            