apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: app
        image: scienceselva:capstone
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080        