apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: scienceselva:capstone
        ports:
        - containerPort: 8080